summon-costs-epearls: true # If enabled, it costs ender pearls to summon a horse
invulnerable-horses: false # If enabled, player horses are invulnerable
horse-upgrade-max-health-multiplier: 1.05 # The modifier used for upgrading horse health