main: net.thederpgamerx.fantasyhorses.main.Main
name: FantasyHorses
author: TheDerpGamerX
version: 0.10
api-version: 1.15
commands: 
 horse:
  usage: /fhorse
  description: Opens horse GUI

permissions:
 fantasyhorses.admin:
  description: Access to all admin commands
  default: false